language: c
dist: focal

env:
  global:
    - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    - CPPLINT_FILTERS='--filter=-readability/casting,-legal/copyright'
    - CPPLINT_FILES='--recursive src/ include/ main.c'

addons:
   apt:
     packages:
      - valgrind
      - python3
      - python3-pip

compiler:
   - clang
   - gcc

script:
   - pip3 install --user cpplint
   - cpplint $CPPLINT_FILTERS $CPPLINT_FILES

   - cmake . && make

   - valgrind $VALGRIND_OPTS ./untitled1 > valgrind.log 2>&1
   - grep -q "no leaks are possible" valgrind.log

