language: c
dist: focal

env:
  global:
    - VALGRIND_OPTS='--leak-check=full --track-origins=yes'

    - CPPLINT_FILTERS='--filter=-readability/casting,-legal/copyright'
    - CPPLINT_FILES='--recursive src/ include/ main.c test/algorithm.cpp'

addons:
   apt:
     packages:
      - valgrind
      - python3
      - python3-pip
      - cppcheck
      - gcc-10
      - g++-10

compiler:
   - clang
   - gcc

script:
   - pip3 install --user cpplint
   - cpplint $CPPLINT_FILTERS $CPPLINT_FILES

   - cppcheck .

   - cmake . && make && make test

   - valgrind $VALGRIND_OPTS ./hw1 > valgrind.log 2>&1
   - cat valgrind.log
   - grep -q "no leaks are possible" valgrind.log

